### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by deekshahegde86** [bezkoder/express-file-upload#1]
TypeError: Cannot read property 'forEach' of undefined
    at D:\reactui\express-file-upload\src\controller\file.controller.js:43:11
    at FSReqCallback.oncomplete (fs.js:155:23)

**Comment by abcbdf** [comment]
> TypeError: Cannot read property 'forEach' of undefined
> at D:\reactui\express-file-upload\src\controller\file.controller.js:43:11
> at FSReqCallback.oncomplete (fs.js:155:23)

I got the same problem. It turns out that I didn't create "const directoryPath = __basedir + "/resources/static/assets/uploads/" this folder. Hope this can help you
